### ISSUE TITLE
Transfer from Barcelona to Frankfurt doesn't work

### ISSUE THREAD

**Issue by martinsillaots** [centre-for-educational-technology/Melange#10]
In the end of the Barcelona chapter Mali’s head is moving from Barcelona to Frankfurt but nothing happens.

**Comment by martinsillaots** [comment]
Why this issue is closed? The map does not work! Make the towns and the names of the towns on the map clickable.

**Comment by sanderaido** [comment]
The map is now clickable, but would still need a visual enhancement to let the player know that they can now travel to Tallinn after visiting all locations. And a hint as to which ones are completed already. I have a few ideas, will try them out.
