### ISSUE TITLE
TL shortcut doesn't work 

### ISSUE THREAD

**Issue by martinsillaots** [centre-for-educational-technology/Melange#15]
There is no access or shortcut to the Tallinn Chapter. Add shortcut key combination for Tallinn Chapter (TL or TAL).

**Comment by martinsillaots** [comment]
What is the shortcut for the Tallinn?

**Comment by sanderaido** [comment]
It's just **TL**

**Comment by martinsillaots** [comment]
Not **TLU** like you suggested in the beginning of this week?

**Comment by sanderaido** [comment]
I forgot about that idea, that’s actually better, I made the change in 0.8.2
