### ISSUE TITLE
Dialogue in the train quits

### ISSUE THREAD

**Issue by martinsillaots** [centre-for-educational-technology/Melange#18]
Dialogue at the train ends when the answer “I donate know” is selected. Is this a bug or a feature?

**Comment by martinsillaots** [comment]
Malte, can you send the structure of this dialogue, because currently we have multiple ends in this dialogue.

**Comment by sanderaido** [comment]
<img width="679" alt="screen shot 2019-01-18 at 13 09 24" src="https://user-images.githubusercontent.com/9868517/51383731-ecf79f80-1b22-11e9-8d8f-041239ced02c.png">
Current state in Unity
