### ISSUE TITLE
Audio files and dialogue tree don't match in #06_LowGlucose dialogue

### ISSUE THREAD

**Issue by sanderai** [centre-for-educational-technology/Melange#23]
* Node 1 is one audio file but split up into nodes 1 and 44 in the dialogue tree - - short entries so can combine nodes
* Same with node 12 and split with 45 - short entries so can combine nodes
* Same with node 16 and split with 46 - short entries so can combine nodes
* Same with node 23 and split with 47 - short entries so can combine nodes
* Same with node 32 and split with 48 - short entries so can combine nodes
* Same with node 41 and split with 49 - long entries so this audio should be split to two nodes

**Comment by sanderaido** [comment]
<img width="789" alt="screen shot 2018-11-29 at 15 31 19" src="https://user-images.githubusercontent.com/9868517/49225262-42011a00-f3ec-11e8-93fc-0c048e333f60.png">

**Comment by sanderaido** [comment]
Ok, I think I found the problem. Although everything is correct in the pdf and xml, it seems that the Unity Dialogue system importer doesn't like the | character. I didn't test this fully, but it seems like the cause because it split the nodes every time it was used in that dialogue. For example

> Really? Cool ... which country can you recommend for someone like me? |Maybe I need to sit down though, I don’t feel well. 

> My BG... my blood glucose, is really low right now. |You know I'm diabetic.

> Yeah, let's go to Fleming's Bar. It's on top of the Fleming's Hotel at Eschenheimer Tor. |If my BG is still low, I can get a dessert or something.
 
I will fix the nodes in Unity then and try the dialogue again.

**Comment by martinsillaots** [comment]
**Malte:** You can delete the „|“. In ChatMapper this character allows the dialogue to pause at these symbols in order break up texts. In MElang-E, we do not really need this feature.
