### ISSUE TITLE
Kinnekswiss different setting

### ISSUE THREAD

**Issue by martinsillaots** [centre-for-educational-technology/Melange#31]
The Park scene is different when playing it second time. First there were girls on the blanket (and the dialogue did not start). Second there are 3 figures on the road, one of them sitting on the bench (and the dialogues does not start). Does the content of the scene depend on dialogue in the modern art museum? Bug or Feature?

**Comment by sanderaido** [comment]
There was a mistake in the sprite order, all sprites were on the same layer and sometimes were hidden behind the background
