### ISSUE TITLE
Dialogue mistake in the tourist office

### ISSUE THREAD

**Issue by martinsillaots** [centre-for-educational-technology/Melange#44]
In the scene IST_#02b_TouristOffice after the Malis sentence: “No no everything is fine I need some information* Mehmet’s previous sentence is repeated: “Is everything OK?” But the options for many are “No, no. I’m not interested in taking a tour.”

**Comment by martinsillaots** [comment]
<img width="810" alt="Dialogue breaks" src="https://user-images.githubusercontent.com/44232616/57020954-9a567500-6c33-11e9-8a4a-5aed186b11fd.png">

**Comment by sanderaido** [comment]
I think there is a mistake in the dialogue files, I assume it is supposed to go to node 7 instead of 8 after 5 and 46. 
![Screen Shot 2019-05-02 at 20 02 42](https://user-images.githubusercontent.com/9868517/57093116-b6cade00-6d15-11e9-991b-0fab2d3b3c6a.png)
