### ISSUE TITLE
NPC’s have no sound

### ISSUE THREAD

**Issue by martinsillaots** [centre-for-educational-technology/Melange#45]
Starting from the scene IST_#04_GalataBridge NPC’s have no sound (Mali has). There is also no sound for nPC’s in the IST_#05_FishMarket scene. In the IST_#06_Kanyon sound is OK.

**Comment by sanderaido** [comment]
This was again caused by umlauts in character names or filenames. Some were even weird "hidden" umlauts that I couldn't see for some reason (there weren't any visible umlauts in the file name but when replacing the filename with one that looked essentially the same, it started working).
