### ISSUE TITLE
No interaction on the final IST scene

### ISSUE THREAD

**Issue by martinsillaots** [centre-for-educational-technology/Melange#46]
In the scene IST_#07_AtÖmer’s characters seams to be interactive but clicking on them nothing happens.

**Comment by sanderaido** [comment]
This is a naming issue with dialogue names, usually the dialogue names are 
`IST_#05a_FishMarket` but the last scene has names without the leading zero like `IST_#7a_AtÖmer's` which causes the dialogue manager to not find the dialogues.

**Comment by martinsillaots** [comment]
Can you rename the sound files? Add missing 0. Saba had a software for renaming files ...

**Comment by sanderaido** [comment]
I renamed and reimported the faulty conversations with a small script, this was easier since it affected nodes and dialogues as well in addition to sound files.
